// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phonezone_backend.Data;

#nullable disable

namespace phonezone_backend.Migrations
{
    [DbContext(typeof(PhoneZoneDBContext))]
    [Migration("20250222121734_fb")]
    partial class fb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("phonezone_backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("phonezone_backend.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("phonezone_backend.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("phonezone_backend.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("phonezone_backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountAmount")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("FinalAmount")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("phonezone_backend.Models.OrderCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<string>("DiscountAmount")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersCoupons");
                });

            modelBuilder.Entity("phonezone_backend.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("phonezone_backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("NewPrice")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("OldPrice")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Stock")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("phonezone_backend.Models.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("BatteryCapacity")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Bluetooth")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Camera")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("CameraFeatures")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("CameraTrueDepth")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ChargingConnectivity")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ChargingSupport")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ChargingTechnology")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Chip")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("FingerprintSensor")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("FrontCamera")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("GPS")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Guarantee")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("InternalMemory")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("NFC")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("NetworkSupport")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("OutstandingFeatures")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("RearCamera")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("SIM")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Screen")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ScreenFeatures")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Sensor")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("SpecialFeatures")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Thumbnails")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("WaterResistant")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("WiFi")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("phonezone_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("phonezone_backend.Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("phonezone_backend.Models.WishListItem", b =>
                {
                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("WishListId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishListItems");
                });

            modelBuilder.Entity("phonezone_backend.Models.Cart", b =>
                {
                    b.HasOne("phonezone_backend.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phonezone_backend.Models.CartItem", b =>
                {
                    b.HasOne("phonezone_backend.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phonezone_backend.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("phonezone_backend.Models.Order", b =>
                {
                    b.HasOne("phonezone_backend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phonezone_backend.Models.OrderCoupon", b =>
                {
                    b.HasOne("phonezone_backend.Models.Coupon", "Coupon")
                        .WithMany("OrderCoupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phonezone_backend.Models.Order", "Order")
                        .WithMany("OrderCoupons")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("phonezone_backend.Models.OrderDetail", b =>
                {
                    b.HasOne("phonezone_backend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phonezone_backend.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("phonezone_backend.Models.Specification", b =>
                {
                    b.HasOne("phonezone_backend.Models.Product", "Product")
                        .WithOne("Specification")
                        .HasForeignKey("phonezone_backend.Models.Specification", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("phonezone_backend.Models.WishList", b =>
                {
                    b.HasOne("phonezone_backend.Models.User", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phonezone_backend.Models.WishListItem", b =>
                {
                    b.HasOne("phonezone_backend.Models.Product", "Product")
                        .WithMany("WishListItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phonezone_backend.Models.WishList", "WishList")
                        .WithMany("WishListItems")
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("phonezone_backend.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("phonezone_backend.Models.Coupon", b =>
                {
                    b.Navigation("OrderCoupons");
                });

            modelBuilder.Entity("phonezone_backend.Models.Order", b =>
                {
                    b.Navigation("OrderCoupons");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("phonezone_backend.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("Specification");

                    b.Navigation("WishListItems");
                });

            modelBuilder.Entity("phonezone_backend.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("phonezone_backend.Models.WishList", b =>
                {
                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
